feat: ban appeal link config
BeccaLyria/discord-bot pull request #1086
Opened 2022-01-09 20:37 UTC by Vyvy-vi

# Pull Request

## Description

This PR adds a config setting for ban appeal link, where a server can provide a link to a Google Form (or other option) for appealing a ban. Then, when a user is banned, if this config is set, Becca includes the value in the DM sent to the user.

## Results
- Appeal link in the DM sent on ban
![Screenshot 2022-01-10 at 1 57 41 AM](https://user-images.githubusercontent.com/62864373/148699802-e7b2f324-ed1e-48ca-933b-328ec1b2236a.png)
- Setting the config link
![Screenshot 2022-01-10 at 2 06 34 AM](https://user-images.githubusercontent.com/62864373/148699838-1a47a1b4-97f8-4bdb-9623-878b6055515d.png)
- Config View Embed
![Screenshot 2022-01-10 at 2 07 20 AM](https://user-images.githubusercontent.com/62864373/148699858-a3cd4082-d062-442a-95ec-06a4315d2051.png)

## Related Issue

Closes #1071

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [x] My contribution DOES require a documentation update.

2022-01-09 20:57 UTC, nhcarrigan requested changes

2022-01-09 20:57 UTC, nhcarrigan commented on src/modules/settings/renderSetting.ts
> +        return value as string;
This is in the wrong place and will break the `automod_channels` and `no_automod_channels` validation. Instead, it should go up on line 33 with the other cases that return `value as string`.

2022-01-09 20:57 UTC, nhcarrigan commented on src/modules/settings/setSetting.ts
> +        break;
This doesn't need a separate switch block, and can be added to the list of cases on line 94.

2022-01-09 20:57 UTC, nhcarrigan commented on src/utils/sendModerationDm.ts
> +      }
```suggestion
      if (server && server.appeal_link.length) {
        embed.addField(
          "You can appeal your ban using this link: ",
          server.appeal_link
        );
      }
```
A few notes here:
- We can run both checks in the single `if` condition so we don't have to nest things.
- `appeal_link` is a string, which means we can assert for truthiness as the only time it would be falsy is if it's an empty string.

2022-01-09 20:57 UTC, nhcarrigan commented on src/utils/sendModerationDm.ts
> +      const server = (await ServerModel.findOne({ serverID })) || null;
A quick note on this one that the config is already fetched and passed to the commands, so we could add it as a parameter for this function and pass it down, rather than having to fetch it again in this module.

That can be refactored in a separate PR, if needed.

2022-01-09 22:32 UTC, Vyvy-vi commented on src/utils/sendModerationDm.ts
> +      const server = (await ServerModel.findOne({ serverID })) || null;
hmm that would make sense...
Could we replace the `guild` param I added in here with the config?

2022-01-10 01:34 UTC, nhcarrigan commented on src/utils/sendModerationDm.ts
> +      const server = (await ServerModel.findOne({ serverID })) || null;
We can do that, yeah. We'll need to get `config.serverName` assigned to `guildName` so the template literal parses correctly.

2022-01-10 01:35 UTC, nhcarrigan commented on src/modules/commands/config/viewSettings.ts
> +    settingsEmbed.addField("Ban Appeal Link", config.appeal_link, true);
```suggestion
    settingsEmbed.addField("Ban Appeal Link", config.appeal_link || "not set", true);
```
Something like this... we need a fallback here for when there is no `appeal_link` value.
Committing this as-is might make the linter mad. Not sure.

2022-01-10 13:20 UTC, merged

2022-01-10 13:20 UTC, nhcarrigan commented
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.