Feat/1201/update mod perms
BeccaLyria/discord-bot pull request #1224
Opened 2022-04-07 17:15 UTC by Vyvy-vi

# Pull Request

## Description

This PR adds a permission check for moderation targets that checks whether they have the same level of permissions as the moderator using the command.

## Related Issue

Closes #1201 

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2022-04-07 17:19 UTC, Vyvy-vi commented
Maybe there should be a different response for this case?

2022-04-07 20:06 UTC, nhcarrigan commented on src/modules/commands/subcommands/moderation/handleBan.ts
> +      typeof targetMember.permissions === "string" ||
We shouldn't need this type assertion here.

The `.fetch()` returns a GuildMember or `null`. We only need it for the member *calling* the command because interactions can be HTTP based, and the type-def is different.

2022-04-10 05:31 UTC, nhcarrigan requested changes
Let's go ahead and get this in.

2022-04-10 05:31 UTC, nhcarrigan approved these changes

2022-04-10 05:31 UTC, merged