FEAT: /post commands
BeccaLyria/discord-bot pull request #1405
Opened 2022-10-10 14:14 UTC by Vyvy-vi

# Pull Request

## Description

This PR adds `/post create`, `/post edit`, `/post delete` commands and an even listener for modal submissions.

## Related Issue

Closes #1089 

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [x] My contribution DOES require a documentation update.

2022-10-10 19:00 UTC, Vyvy-vi commented
There are a few open questions I have related to this PR:
- Q) How do we prevent the user from deleting or updating messages sent by Becca that weren't created using the `/post create` command? Eg: the reaction role message. Could we perhaps store an object in the DB that contains the IDs of post messages?
- Q) Some of the methods used to resolve channels and messages throw an error when they're not found. Should we add an extra try-catch block for this, or is there some other way of checking this so that we can send detailed error messages to the user?
- Q) Is there a way to fetch a Message with just the messageId without filtering through all the channels in a guild? (The modal generated by the `/post edit` command has a customId that has format - `pe-${channelId}-${messageId}`). Also, should these IDs be in cammelCase?

2022-10-18 21:11 UTC, naomi-lgbt commented
> Q) How do we prevent the user from deleting or updating messages sent by Becca that weren't created using the /post create command? Eg: the reaction role message. Could we perhaps store an object in the DB that contains the IDs of post messages?

Given that this is locked to the Manage Guild permission, I wouldn't worry too much about this.

> Q) Some of the methods used to resolve channels and messages throw an error when they're not found. Should we add an extra try-catch block for this, or is there some other way of checking this so that we can send detailed error messages to the user?

For the `.fetch()` calls, we can chain a `.catch(()=>null)` and then assert for existence. If it doesn't exist, we can respond with a message instead of an error.

Q) Is there a way to fetch a Message with just the messageId without filtering through all the channels in a guild? (The modal generated by the /post edit command has a customId that has format - pe-${channelId}-${messageId}).

No, but you should be able to resolve the channel and then resolve the message from the channel.

Q) Since there is a 17.1% duplication in the PR ( aaaa sonarcloud isn't happy :( ), would it be alright if I extract some of the permission checks into the run method in post.js or add a function in utils to do those checks and use that function in all the files?

Don't worry too much about the duplication that's not a concern for us at this time.

2022-10-20 21:33 UTC, naomi-lgbt commented
@Vyvy-vi is this one ready for review?

2022-10-20 21:57 UTC, Vyvy-vi commented
This needs addition of .catch() for error handling in some parts. Maybe it can be reviewed once those changes have been commited?

2022-10-20 22:07 UTC, naomi-lgbt commented
Sure thing~! Just let me know when~!

2022-10-30 18:49 UTC, naomi-lgbt commented
Is this ready now?

2022-10-31 12:34 UTC, Vyvy-vi commented
yes, it's ready!

2022-11-02 17:13 UTC, naomi-lgbt requested changes

2022-11-02 17:13 UTC, naomi-lgbt commented on src/commands/post.ts
> +        .addIntegerOption((option) =>
```suggestion
        .addStringOption((option) =>
```

2022-11-02 17:13 UTC, naomi-lgbt commented on src/commands/post.ts
> +              ChannelType.GuildPrivateThread
```suggestion
              ChannelType.GuildText,
              ChannelType.GuildAnnouncement,
              ChannelType.AnnouncementThread,
              ChannelType.PublicThread,
              ChannelType.PrivateThread,
```
Replace with the newer type names.

2022-11-02 17:13 UTC, naomi-lgbt commented on src/commands/subcommands/post/handleDelete.ts
> +    await interaction.reply({ content: t("commands:post.delete.success") });
```suggestion
    await interaction.deferReply({ ephemeral: true });
    const { member, guild } = interaction;

    if (!guild) {
      await interaction.editReply({
        content: getRandomValue(t("responses:missingGuild")),
      });
      return;
    }

    const link = interaction.options.getString("link", true).split("/");
    const channelId = link[link.length - 2];
    const messageId = link[link.length - 1];

    const channel = guild.channels.resolve(channelId);

    if (
      !member ||
      typeof member.permissions === "string" ||
      !member.permissions.has(PermissionFlagsBits.ManageGuild)
    ) {
      await interaction.editReply({
        content: getRandomValue(t("responses:noPermission")),
      });
      return;
    }
    if (!channel || !("messages" in channel)) {
      await interaction.reply({
        content: t("commands:post.delete.invalid"),
      });
      return;
    }

    const targetMessage = await channel.messages
      .fetch(messageId)
      .catch(() => null);

    if (!targetMessage) {
      await interaction.editReply({
        content: t("commands:post.delete.doesnt-exist"),
      });
      return;
    }

    if (targetMessage.author !== Becca.user || !targetMessage.deletable) {
      await interaction.editReply({
        content: t("commands:post.delete.cant-delete"),
      });
      return;
    }
    await targetMessage.delete();
    await interaction.reply({ content: t("commands:post.delete.success") });
```

Ephemeral response, and await delete call.

2022-11-02 17:13 UTC, naomi-lgbt commented on src/commands/subcommands/post/handleEdit.ts
> +    }
```suggestion
    if (!guild) {
      await interaction.reply({
        content: getRandomValue(t("responses:missingGuild")),
        ephemeral: true,
      });
      return;
    }

    const link = interaction.options.getString("link", true).split("/");
    const channelId = link[link.length - 2];
    const messageId = link[link.length - 1];

    const channel = guild.channels.resolve(channelId);

    if (
      !member ||
      typeof member.permissions === "string" ||
      !member.permissions.has(PermissionFlagsBits.ManageGuild)
    ) {
      await interaction.reply({
        content: getRandomValue(t("responses:noPermission")),
        ephemeral: true,
      });
      return;
    }
    if (!channel || !("messages" in channel)) {
      await interaction.reply({
        content: t("commands:post.edit.invalid"),
      });
      return;
    }

    const targetMessage = await channel.messages
      .fetch(messageId)
      .catch(() => null);

    if (!targetMessage) {
      await interaction.reply({
        content: t("commands:post.edit.doesnt-exist"),
        ephemeral: true,
      });
      return;
    }

    if (targetMessage.author !== Becca.user) {
      await interaction.reply({
        content: t("commands:post.edit.cant-edit"),
        ephemeral: true,
      });
      return;
    }
```

Ephemeral.

2022-11-03 13:26 UTC, Vyvy-vi commented on src/commands/post.ts
> +        .addIntegerOption((option) =>
🤦

2022-11-03 17:56 UTC, naomi-lgbt requested changes

2022-11-03 17:56 UTC, naomi-lgbt commented on src/commands/post.ts
> +              ChannelType.PrivateThread,
```suggestion
              ChannelType.PrivateThread
```
One day I'll make suggestions on GitHub and **not** screw up the linter lol

2022-11-03 21:00 UTC, Vyvy-vi commented on src/commands/post.ts
> +              ChannelType.PrivateThread,
lol
🤔 I wonder if there can be a github action that lints suggestions

2022-11-03 21:08 UTC, naomi-lgbt approved these changes
Okay, this should be good to go.

2022-11-03 21:11 UTC, merged

2022-11-03 21:11 UTC, naomi-lgbt commented
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt)