feat/forum-channel-support-for-suggestions
BeccaLyria/discord-bot pull request #1413
Opened 2022-10-19 12:42 UTC by j-dogcoder

# Pull Request

## Description
Adds Forum support for suggesting 

## Related Issue

Closes #1389 

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2022-10-19 12:43 UTC, j-dogcoder commented
@naomi-lgbt, does this work??? I think it should...

2022-10-19 19:41 UTC, naomi-lgbt commented
This is actually blocked again - I need to update d.js to the latest version to get proper forum support.

2022-10-19 20:29 UTC, naomi-lgbt commented
Okay, this will need a rebase to get the latest d.js version - and then we can implement proper forum channel support.

2022-10-20 02:27 UTC, j-dogcoder commented
Should be better now @naomi-lgbt?

2022-10-20 03:48 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +    ) as TextChannel || ForumChannel ;
```suggestion
    ) as TextChannel | ForumChannel ;
```

This is going to open up a whole can of worms when you commit it - but `||` is the logical OR, `|` is the type operator.

2022-10-20 11:42 UTC, j-dogcoder commented on src/commands/subcommands/community/handleSuggest.ts
> +    ) as TextChannel || ForumChannel ;
Got it... do you want me to leave it or change it?

2022-10-20 13:08 UTC, j-dogcoder commented on src/commands/subcommands/community/handleSuggest.ts
> +    ) as TextChannel || ForumChannel ;
@naomi-lgbt The compiler only likes a single `|`

2022-10-20 16:11 UTC, naomi-lgbt requested changes

2022-10-20 16:11 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +      ) as TextChannel) || ForumChannel;
```suggestion
    const suggestionChannel =
      guild.channels.cache.find(
        (el) => el.id === config.suggestion_channel
       as TextChannel) | ForumChannel;
```

This is not correct. The code is currently saying `suggestionChannel` should be:
- The channel resolved from the cache as `TextChannel` OR
- The value of `ForumChannel`.

We need to use `|`, which tells TypeScript that `suggestionChannel` is either the type `TextChannel` or `ForumChannel`.

This **will** create compiler errors, because forum channels have different methods than text based channels, and as such the logic further down will need to be updated.

2022-10-20 16:11 UTC, naomi-lgbt commented on src/commands/subcommands/manage/handleSuggestion.ts
> +      (suggestionChannel as TextChannel) || ForumChannel
```suggestion
      suggestionChannel as TextChannel | ForumChannel
```

See above.

2022-10-20 16:38 UTC, j-dogcoder commented on src/commands/subcommands/community/handleSuggest.ts
> +      ) as TextChannel) || ForumChannel;
That makes more sense... the compiler errors threw me off

2022-10-20 16:58 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +       as TextChannel) | ForumChannel;
```suggestion
    const suggestionChannel =
      guild.channels.cache.find(
        (el) => el.id === config.suggestion_channel)
       as TextChannel | ForumChannel;
```
Whoops

2022-10-22 21:37 UTC, j-dogcoder commented
Hey @naomi-lgbt, this should be ready again...

2022-10-22 22:38 UTC, naomi-lgbt requested changes

2022-10-22 22:38 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +       as TextChannel | ForumChannel;
```suggestion
    const suggestionChannel = guild.channels.cache.find(
      (el) => el.id === config.suggestion_channel
    ) as TextChannel | ForumChannel;
```

The formatting is breaking this apparently. We'll still need to update the actual logic for sending the suggestion.

2022-10-23 20:18 UTC, j-dogcoder commented
Logic coming your way shortly

2022-10-25 13:05 UTC, j-dogcoder commented
@naomi-lgbt, I think that you should be able to send to forum channels with the logic how it is?

2022-10-25 18:01 UTC, naomi-lgbt commented
<img width="507" alt="image" src="https://user-images.githubusercontent.com/63889819/197847522-adfa443d-4b56-421a-a17b-f3ddd8d9edb4.png">

Nope - you'll see a compiler error. Forum channels don't have a `.send()` method.

It looks like we'll need to check if the channel type is equal to `ChannelTypes.ForumChannel` (or whatever the enum calls it) and if so, run logic to create a new channel as a thread with this channel as the parent.

May need to do some extra research here, as the object doesn't appear to have a method to do this itself.

2022-10-28 08:09 UTC, Vyvy-vi commented
The `GuildForumThreadManager` object is returned by `ForumChannel.threads` provides a `create` method to make a new thread https://discord.js.org/#/docs/discord.js/main/class/GuildForumThreadManager?scrollTo=create

2022-10-28 08:11 UTC, naomi-lgbt commented
Ah, that's where it was buried.

2022-10-28 08:18 UTC, Vyvy-vi commented
I wonder if the create method would allow an embed to be the first message posted in a forum thread 🤔

2022-10-28 08:19 UTC, naomi-lgbt commented
I'd assume so - looks like it takes `message` with the standard message properties.

2022-11-01 12:59 UTC, j-dogcoder commented
I think I am getting somewhere with this...

2022-11-01 12:59 UTC, j-dogcoder commented
I will push some changes in a bit...

2022-11-01 13:00 UTC, naomi-lgbt commented
No rush!!

2022-11-01 14:29 UTC, j-dogcoder commented
@naomi-lgbt, having some issues again... can you take a look?

2022-11-01 16:07 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +    if (suggestionChannel.type === TextChannel) {
Two things:

- One, we'll want to invert the conditional here. `if channel is forum` instead of `if channel is text` BECAUSE....
- We need to check this against the `ChannelTypes` enum - and checking `ChannelTypes.ForumChannel` is easier than checking all valid text channel types.

2022-11-01 16:11 UTC, naomi-lgbt requested changes

2022-11-01 16:11 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +        type: "GUILD_PUBLIC_THREAD",
There's probably an enum for this. `ThreadChannelTypes.PublicThread` probably.

2022-11-01 16:11 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +          embeds: [suggestionEmbed],
Huh. I wonder if we need to spread this to get the raw JSON.

2022-11-01 16:11 UTC, naomi-lgbt commented on src/commands/subcommands/community/handleSuggest.ts
> +        .react(Becca.configs.yes)
It looks like we'll need to fetch the message from the channel, and add the reaction to that.

`sentMessage` here is the thread instance, not the first message.

2022-11-14 01:06 UTC, naomi-lgbt approved these changes
Dev server doesn't have forum access so... guess we're testing in production!!!

2022-11-14 01:06 UTC, merged