Feature: Create an echo command.
BeccaLyria/discord-bot pull request #1901
Opened 2023-09-18 22:10 UTC by a2937

# Pull Request

## Description

It creates an command that allows members to send a message from Becca's account. 

## Related Issue
Closes #1895

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [X] My contribution DOES require a documentation update.

Note: It's not been thoroughly tested because I was having some unexpected difficulties with Prisma. Additionally it appears that setting the permission for the command is impossible without adjusting the permissions for *all* the sub commands.

2023-09-18 22:26 UTC, naomi-lgbt requested changes
We'll also need to validate that the member calling this command has the `Manage Messages` permission.

2023-09-18 22:26 UTC, naomi-lgbt commented on src/commands/subcommands/misc/handleEcho.ts
> +    interaction.ephemeral = true;
```suggestion
    await interaction.deferReply({ ephemeral: true });
```

This should be a deferred reply.

2023-09-18 22:26 UTC, naomi-lgbt commented on src/commands/subcommands/misc/handleEcho.ts
> +    const input = interaction.options.getString("input") || "";
```suggestion
    const input = interaction.options.getString("input", true);
```

It's a required input, so we call tell the `.getString()` method such and avoid needing a fallback.

2023-09-18 22:26 UTC, naomi-lgbt commented on src/commands/subcommands/misc/handleEcho.ts
> +    });
This isn't quite what we're looking for.

The `input` should be sent as a message to the `interaction.channel` (will need to validate the channel exists and is a text channel).

The response to the interaction should be a confirmation or such.

2023-09-18 23:27 UTC, a2937 commented on src/commands/subcommands/misc/handleEcho.ts
> +    const input = interaction.options.getString("input") || "";
Right. Yeah it shouldn't need a fallback.

2023-09-18 23:35 UTC, naomi-lgbt requested changes

2023-09-18 23:35 UTC, naomi-lgbt commented on src/commands/subcommands/misc/handleEcho.ts
> +      //TODO: Use the translation system to get the text.
We can use the `responses:noPermission` translation value (we'll need to use the `getRandomValue` util for that)

2023-09-18 23:35 UTC, naomi-lgbt commented on src/commands/subcommands/misc/handleEcho.ts
> +      interaction.memberPermissions?.has(PermissionFlagsBits.ManageMessages)
A couple of things on this one.

- Let's invert the boolean, such that we can use early return patterns. "If not has permissions, editReply 'cannot use' and return"
- The `interaction` payload is validated by a typeguard, which means you can use `interaction.member.permissions.has` instead - with no optional chaining.

2023-09-18 23:44 UTC, a2937 commented on src/commands/subcommands/misc/handleEcho.ts
> +      interaction.memberPermissions?.has(PermissionFlagsBits.ManageMessages)
Done.

2023-09-18 23:44 UTC, a2937 commented on src/commands/subcommands/misc/handleEcho.ts
> +      //TODO: Use the translation system to get the text.
Did I do this right?

2023-09-18 23:52 UTC, naomi-lgbt requested changes
Should be the last nitpick

2023-09-18 23:52 UTC, naomi-lgbt commented on src/commands/subcommands/misc/handleEcho.ts
> +    }
```suggestion
    if (
      !interaction.member.permissions.has(PermissionFlagsBits.ManageMessages)
    ) {
      await interaction.editReply({
        content: tFunctionArrayWrapper(t, "responses:noPermission"),
      });
      return;
    }
    interaction.channel.send(input);
    await interaction.editReply({
      content: "Your message has been posted.",
    });
```

2023-09-19 00:08 UTC, naomi-lgbt commented on src/commands/subcommands/misc/handleEcho.ts
> +      //TODO: Use the translation system to get the text.
Should be correct, yes!

2023-09-19 20:31 UTC, naomi-lgbt approved these changes

2023-09-19 20:31 UTC, merged

2023-09-19 20:31 UTC, naomi-lgbt commented
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt)