messageUpdate triggering on false positives
BeccaLyria/discord-bot pull request #529
Opened 2021-02-22 05:12 UTC by bagladivyang03

# Pull Request

## Description:
[BUG] - messageUpdate triggering on false positives #528

## Related Issue:

Closes #XXXXX

## Scope:

Did you remember to update the `package.json` version number?

- [ ] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [ ] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [ ] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [ ] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

## Documentation:

For _any_ version updates, please verify if the [documentation page](https://beccalyria.nhcarrigan.com) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2021-02-22 05:14 UTC, nhcarrigan requested changes
A couple of quick things:

- You'll need to fix the linting issues for the CI to pass.
- After you've fixed the linting issues, you'll need to bump the version. You can do this with `npm version patch` and a commit will be generated which you'll push up to your branch.

2021-02-22 05:14 UTC, bagladivyang03 commented
#528

2021-02-22 05:17 UTC, bagladivyang03 commented
> A couple of quick things:
> 
> * You'll need to fix the linting issues for the CI to pass.
> * After you've fixed the linting issues, you'll need to bump the version. You can do this with `npm version patch` and a commit will be generated which you'll push up to your branch.

Could u pls tell me in brief how to do this I m a beginner. So it would be great if you could help me!

2021-02-22 14:09 UTC, nhcarrigan commented
Are you working on this directly through GitHub? If so, I recommend cloning it locally so you can use the included tooling to fix the linting issues.

2021-02-22 14:26 UTC, nhcarrigan requested changes
Added a suggestion you can commit through GitHub to resolve the linting issue.

2021-02-22 14:26 UTC, nhcarrigan commented on src/events/onMessageUpdate.ts
> +    }
```suggestion
    // validation added if newMessage and oldMessage are same
    if (
      oldMessage.content &&
      newMessage.content &&
      oldMessage.content === newMessage.content
    ) {
      return;
    }
```

2021-02-22 14:35 UTC, nhcarrigan approved these changes
Looks good to me. Tested locally, resolves the false positives.

Will merge when the CI passes - I went ahead and pushed up the version commit too.

2021-02-22 14:35 UTC, nhcarrigan commented
@all-contributors please add @bagladivyang03 for code

2021-02-22 14:36 UTC, bagladivyang03 commented
@nhcarrigan Thanks for the help.

2021-02-22 14:37 UTC, nhcarrigan commented
@all-contributors please add @bagladivyang03 for code

2021-02-22 14:38 UTC, merged

2021-02-22 14:39 UTC, nhcarrigan commented
Congrats on your first pull request (PR).

Thank you for your contribution to the page. We are happy to accept these changes and look forward to future contributions.

2021-02-22 14:41 UTC, nhcarrigan commented
Try this again...

@all-contributors please add @bagladivyang03 for code

2021-02-23 07:37 UTC, nhcarrigan commented
Try this again...

@all-contributors please add @bagladivyang03 for code