Corrected the order of DM Logic and Ban Action in ban.ts
BeccaLyria/discord-bot pull request #607
Opened 2021-05-04 16:17 UTC by Zipher007

## Description:

In this, the code for the DM Logic and the Ban action is switched and put in the right order for correct execution.

## Related Issue:

Closes #606

2021-05-04 16:20 UTC, nhcarrigan requested changes
Go ahead and commit these suggestions to fix the linter errors.

2021-05-04 16:20 UTC, nhcarrigan commented on src/commands/moderation/ban.ts
> +
```suggestion

```

2021-05-04 16:20 UTC, nhcarrigan commented on src/commands/moderation/ban.ts
> +
```suggestion

```

2021-05-04 16:24 UTC, Zipher007 commented
are these linter errors due the spaces in the lines ?

2021-05-04 16:26 UTC, nhcarrigan commented
They are, yes - the empty lines should be empty so the linter wanted the spaces removed.

2021-05-04 16:27 UTC, Zipher007 commented
> They are, yes - the empty lines should be empty so the linter wanted the spaces removed.

Oh I see. In the tests also, it was telling to delete the spaces!
Now I understand the importance of seeing the tests for a particular project !!

2021-05-04 18:40 UTC, Zipher007 commented
Thank you so much @nhcarrigan  for guiding me!  
Feels really good after helping, even if it was a small issue😃

2021-05-04 18:41 UTC, nhcarrigan commented
Glad to help! I'll pull this down sometime today to test it. :)

2021-05-04 19:23 UTC, Zipher007 commented
> Glad to help! I'll pull this down sometime today to test it. :)

Hope it works fine now !!

2021-05-05 22:51 UTC, nhcarrigan approved these changes

2021-05-05 22:58 UTC, merged