Added extensions to prevent the bot from blocking words that end with…
BeccaLyria/discord-bot pull request #802
Opened 2021-09-04 11:01 UTC by AbhijithGanesh

… code extensions related to programming

# Pull Request

## Description

## Related Issue

Closes #801

## Scope

Did you remember to update the `package.json` version number?

- [❌] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [✅ ] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [16.14.1] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [ ] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [✅ ] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2021-09-04 14:40 UTC, nhcarrigan requested changes
A quick tweak. :)

2021-09-04 14:40 UTC, nhcarrigan commented on src/listeners/linksListener.ts
> +        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|py|js|html|css|scss|ts|rb|cpp|c|h|vue|java|rs|asp|ashx|php|pl|xml|rss)[a-z]{3,4}|io|me|gg|to|uk|be|in|eu|ru|us|za)))(:[0-9]{1,5})?(
```suggestion
        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|html|css|scss|cpp|vue|java|asp|ashx|php|xml|rss)[a-z]{3,4}|io|me|gg|to|uk|be|in|eu|ru|us|za)))(:[0-9]{1,5})?(.*\s+|\/|$)/gi;
```
Bot doesn't trigger on 2-letter domains.

2021-09-07 14:28 UTC, AbhijithGanesh commented on src/listeners/linksListener.ts
> +        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|py|js|html|css|scss|ts|rb|cpp|c|h|vue|java|rs|asp|ashx|php|pl|xml|rss)[a-z]{3,4}|io|me|gg|to|uk|be|in|eu|ru|us|za)))(:[0-9]{1,5})?(
How do I add regex for two letter domains ?

2021-09-07 16:30 UTC, AbhijithGanesh commented on src/listeners/linksListener.ts
> +        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|py|js|html|css|scss|ts|rb|cpp|c|h|vue|java|rs|asp|ashx|php|pl|xml|rss)[a-z]{3,4}|io|me|gg|to|uk|be|in|eu|ru|us|za)))(:[0-9]{1,5})?(
I have fixed it Nicholas, please check.

2021-09-07 16:36 UTC, nhcarrigan requested changes

2021-09-07 16:36 UTC, nhcarrigan commented on src/listeners/linksListener.ts
> +        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|html|rss|csh|act|ash|rby|pyc|java|vue|php|ashx|xml|rss|cpp|scss|vue|class|ogg|wav|wpp|pkg|deb|rpm|tar.gz|zip|dmg|iso|toast|db.sqlit
```suggestion
        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|html|rss|csh|act|ash|rby|pyc|java|vue|php|ashx|xml|rss|cpp|scss|vue|ogg|wav|wpp|pkg|deb|rpm|zip|dmg|iso|csv|mdb|sql|tar|msg|emlx|vcf|bat|apk|exe|wsf|fnt|font|gif|bmp|icon|jpeg|tiff|asp|aspx|cer|htm|jsp|rss|key|pps|ppt|pptx|odp|xlsx|dll|bak|cab|cfg|ini|drv|icns|tmp|cur|avi|flv|mpg|mpeg|swf|mov|doc|docx|pdf|rtx|tex|wpd|)[a-z]{3,4}|io|me|gg|to|uk|be|in|eu|ru|us|za)))(:[0-9]{1,5})?(.*\s+|\/|$)/gi;
```

Only TLDs between 3 and 4 characters are flagged, so we can remove some of these.

2021-09-07 16:38 UTC, nhcarrigan commented on src/listeners/linksListener.ts
> +        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|html|rss|csh|act|ash|rby|pyc|java|vue|php|ashx|xml|rss|cpp|scss|vue|class|ogg|wav|wpp|pkg|deb|rpm|tar.gz|zip|dmg|iso|toast|db.sqlit
To confirm, adding the two-character domains *blocks* them. Are you intending to block additional things?

2021-09-07 17:43 UTC, AbhijithGanesh commented on src/listeners/linksListener.ts
> +        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|html|rss|csh|act|ash|rby|pyc|java|vue|php|ashx|xml|rss|cpp|scss|vue|class|ogg|wav|wpp|pkg|deb|rpm|tar.gz|zip|dmg|iso|toast|db.sqlit
oh wait the 2 letter domains are ones that will be blocked
I will reverse them right now.

2021-09-07 18:08 UTC, nhcarrigan submitted a review, later dismissed
Looks good to me.
Will rebase and merge when I have the time.

2021-09-07 18:08 UTC, nhcarrigan commented on src/listeners/linksListener.ts
> +        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|html|rss|csh|act|ash|rby|pyc|java|vue|php|ashx|xml|rss|cpp|scss|vue|cgi|ogg|wav|wpp|pkg|deb|rpm|zip|dmg|iso|csv|mdb|sql|tar|msg|eml
```suggestion
        /(^|\s+)(([a-z]+:\/\/)?(([a-z0-9-]+\.)+((?!txt|json|css|jsx|html|rss|csh|act|ash|rby|pyc|java|vue|php|ashx|xml|rss|cpp|scss|vue|cgi|ogg|wav|wpp|pkg|deb|rpm|zip|dmg|iso|csv|mdb|sql|tar|msg|emlx|vcf|bat|apk|exe|wsf|fnt|font|gif|bmp|icon|jpeg|tiff|asp|aspx|cer|htm|jsp|rss|key|pps|ppt|pptx|odp|xlsx|dll|bak|cab|cfg|ini|drv|icns|tmp|cur|avi|flv|mpg|mpeg|swf|mov|doc|docx|pdf|rtx|tex|wpd|)[a-z]{3,4}|io|me|gg|to|uk|be|in|eu|ru|us|za))(:[0-9]{1,5})?(.*\s+|\/|$)/gi;
```

2021-09-07 18:18 UTC, nhcarrigan approved these changes

2021-09-07 18:18 UTC, merged

2021-09-07 18:19 UTC, nhcarrigan commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.