Add Nickname Support for Thanking, and migrated thanksListener to Gui…
BeccaLyria/discord-bot pull request #849
Opened 2021-09-28 17:33 UTC by helloimalastair

# Pull Request

## Description

Changes the ThanksListener, to allow support for nicknames when sending a thanks response. Migrated from `message.mentions.users` to `message.mentions.members`.

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2021-09-28 17:37 UTC, nhcarrigan requested changes

2021-09-28 17:37 UTC, nhcarrigan commented on src/listeners/thanksListener.ts
> +      if (!thanksRegex.test(content) || !mentions.members.size) {
```suggestion
      if (!thanksRegex.test(content) || !mentions.members?.size) {
```

Unlike `users`, `members` can be undefined (as is the case in DMs, which Becca doesn't support) - using optional chaining here will invoke the early return and resolve the build error.

2021-09-30 04:52 UTC, nhcarrigan approved these changes
This is looking good to me. @helloimalastair did you have more you wanted to do? Or is this good to merge?

2021-09-30 04:55 UTC, helloimalastair commented
> 
> 
> This is looking good to me. @helloimalastair did you have more you wanted to do? Or is this good to merge?

Nothing that I can think of, but I try to keep different changes in different pull requests, so if I come up with something, I'll add another one.

2021-09-30 04:59 UTC, merged

2021-09-30 05:00 UTC, nhcarrigan commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.