Changed the link of contribution guidlines in the PR Template
BeccaLyria/discord-bot pull request #872
Opened 2021-10-03 21:32 UTC by MukulKolpe

# Pull Request

## Description

Changed the link of contributing guidelines from CONTRIBUTING.md to the [contribute.md](https://docs.beccalyria.com/#/contribute.md) from the docs in the `PULL_REQUEST_TEMPLATE.md`

## Related Issue

Closes #869 

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2021-10-03 21:33 UTC, nhcarrigan commented
Blocked pending https://github.com/BeccaLyria/discord-documentation/issues/560

2021-10-03 21:36 UTC, nhcarrigan commented
Heya @MukulKolpe, 

This looks good and will be approved/merged once unblocked - I've gone ahead and added the `hacktoberfest-accepted` label so you are credited for your contribution here without having to wait. 🙂

2021-10-03 21:55 UTC, MukulKolpe commented
Hey, Thank you @nhcarrigan, really appreciate that....Looking forward to keeping on contributing here😀

2021-10-04 06:00 UTC, nhcarrigan requested changes
Quick tweak.

2021-10-04 06:00 UTC, nhcarrigan commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Before contributing, please read our contributing guidelines https://docs.beccalyria.com/#/contribute.md -->
```suggestion
<!-- Before contributing, please read our contributing guidelines https://docs.beccalyria.com/#/contribute -->
```

2021-10-04 13:31 UTC, nhcarrigan approved these changes
Looks good to me!

2021-10-04 13:41 UTC, merged